name: CD

on:
  push:
    tags:
      - "*"

jobs:
  changelog:
    name: Changelog
    runs-on: ubuntu-latest

    outputs:
      changelog: ${{ steps.changed-files.outputs.all_changed_files }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Get changed files
        id: changed-files
        uses: tj-actions/changed-files@v35.9.1

      - name: Changelog
        run: |
          echo ${{ steps.changed-files.outputs.all_changed_files }}
  build:
    name: build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Install Rust
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          components: rustfmt, clippy
      - name: Build and Test
        run: |
          cargo build --verbose
          cargo test --verbose

  publish:
    name: Publish
    runs-on: ubuntu-latest
    needs: [changelog, build]
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Publish
        if: startsWith(github.ref, 'refs/tags/')
        run: |
          cargo publish --no-verify
        env:
          CARGO_REGISTRY_TOKEN: ${{ secrets.CARGO_REGISTRY_TOKEN }}
