name: Continuous integration

on:
  pull_request:
    branches: main
  push:
    branches: main

env:
  CARGO_TERM_COLOR: always
  CARGO_INCREMENTAL: 0

jobs:
  changelog:
    name: Changelog
    runs-on: ubuntu-latest

    outputs:
      changelog: ${{ steps.changed-files.outputs.all_changed_files }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          fetch-depth: 2

      - name: Get changed files
        id: changed-files
        uses: tj-actions/changed-files@v35.9.1

      - name: Changelog
        run: |
          echo ${{ steps.changed-files.outputs.all_changed_files }}

  test-core:
    name: Test Core
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Build
        run: cargo build --verbose

      - name: Test
        run: cargo test --verbose
